#pragma once

#include <param/paramdef/ACTIONBUTTON_PARAM_ST.hpp>
#include <param/paramdef/AI_ANIM_TBL_PARAM.hpp>
#include <param/paramdef/AI_ATTACK_PARAM_ST.hpp>
#include <param/paramdef/AI_ODDS_PARAM.hpp>
#include <param/paramdef/AI_SOUND_PARAM_ST.hpp>
#include <param/paramdef/AI_STANDARD_INFO_BANK.hpp>
#include <param/paramdef/ASSET_GEOMETORY_PARAM_ST.hpp>
#include <param/paramdef/ASSET_MATERIAL_SFX_PARAM_ST.hpp>
#include <param/paramdef/ASSET_MODEL_SFX_PARAM_ST.hpp>
#include <param/paramdef/ATK_PARAM_ST.hpp>
#include <param/paramdef/ATTACK_ELEMENT_CORRECT_PARAM_ST.hpp>
#include <param/paramdef/AUTO_CREATE_ENV_SOUND_PARAM_ST.hpp>
#include <param/paramdef/BASECHR_SELECT_MENU_PARAM_ST.hpp>
#include <param/paramdef/BEHAVIOR_PARAM_ST.hpp>
#include <param/paramdef/BONFIRE_WARP_PARAM_ST.hpp>
#include <param/paramdef/BONFIRE_WARP_SUB_CATEGORY_PARAM_ST.hpp>
#include <param/paramdef/BONFIRE_WARP_TAB_PARAM_ST.hpp>
#include <param/paramdef/BUDDY_PARAM_ST.hpp>
#include <param/paramdef/BUDDY_STONE_PARAM_ST.hpp>
#include <param/paramdef/BUDGET_PARAM_ST.hpp>
#include <param/paramdef/BULLET_CREATE_LIMIT_PARAM_ST.hpp>
#include <param/paramdef/BULLET_PARAM_ST.hpp>
#include <param/paramdef/CACL_CORRECT_GRAPH_ST.hpp>
#include <param/paramdef/CAMERA_FADE_PARAM_ST.hpp>
#include <param/paramdef/CEREMONY_PARAM_ST.hpp>
#include <param/paramdef/CHARACTER_INIT_PARAM.hpp>
#include <param/paramdef/CHARMAKEMENUTOP_PARAM_ST.hpp>
#include <param/paramdef/CHARMAKEMENU_LISTITEM_PARAM_ST.hpp>
#include <param/paramdef/CHR_ACTIVATE_CONDITION_PARAM_ST.hpp>
#include <param/paramdef/CHR_MODEL_PARAM_ST.hpp>
#include <param/paramdef/CLEAR_COUNT_CORRECT_PARAM_ST.hpp>
#include <param/paramdef/COMMON_SYSTEM_PARAM_ST.hpp>
#include <param/paramdef/COOL_TIME_PARAM_ST.hpp>
#include <param/paramdef/CS_AA_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_DECAL_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_DOF_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_EFFECT_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_GRAPHICS_CONFIG_PARAM_ST.hpp>
#include <param/paramdef/CS_KEY_ASSIGN_MENUITEM_PARAM.hpp>
#include <param/paramdef/CS_LIGHTING_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_MOTION_BLUR_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_RAYTRACING_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_REFLECTION_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_SHADER_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_SHADOW_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_SSAO_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_TEXTURE_FILTER_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_VOLUMETRIC_EFFECT_QUALITY_DETAIL.hpp>
#include <param/paramdef/CS_WATER_QUALITY_DETAIL.hpp>
#include <param/paramdef/CUTSCENE_GPARAM_TIME_PARAM_ST.hpp>
#include <param/paramdef/CUTSCENE_GPARAM_WEATHER_PARAM_ST.hpp>
#include <param/paramdef/CUTSCENE_MAP_ID_PARAM_ST.hpp>
#include <param/paramdef/CUTSCENE_TEXTURE_LOAD_PARAM_ST.hpp>
#include <param/paramdef/CUTSCENE_TIMEZONE_CONVERT_PARAM_ST.hpp>
#include <param/paramdef/CUTSCENE_WEATHER_OVERRIDE_GPARAM_ID_CONVERT_PARAM_ST.hpp>
#include <param/paramdef/DECAL_PARAM_ST.hpp>
#include <param/paramdef/DEFAULT_KEY_ASSIGN.hpp>
#include <param/paramdef/DIRECTION_CAMERA_PARAM_ST.hpp>
#include <param/paramdef/ENEMY_COMMON_PARAM_ST.hpp>
#include <param/paramdef/ENEMY_STANDARD_INFO_BANK.hpp>
#include <param/paramdef/ENV_OBJ_LOT_PARAM_ST.hpp>
#include <param/paramdef/EQUIP_MTRL_SET_PARAM_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_ACCESSORY_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_CUSTOM_WEAPON_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_GEM_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_GOODS_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_PROTECTOR_ST.hpp>
#include <param/paramdef/EQUIP_PARAM_WEAPON_ST.hpp>
#include <param/paramdef/ESTUS_FLASK_RECOVERY_PARAM_ST.hpp>
#include <param/paramdef/EVENT_FLAG_USAGE_PARAM_ST.hpp>
#include <param/paramdef/FACE_PARAM_ST.hpp>
#include <param/paramdef/FACE_RANGE_PARAM_ST.hpp>
#include <param/paramdef/FE_TEXT_EFFECT_PARAM_ST.hpp>
#include <param/paramdef/FINAL_DAMAGE_RATE_PARAM_ST.hpp>
#include <param/paramdef/FOOT_SFX_PARAM_ST.hpp>
#include <param/paramdef/GAME_AREA_PARAM_ST.hpp>
#include <param/paramdef/GAME_INFO_PARAM.hpp>
#include <param/paramdef/GAME_SYSTEM_COMMON_PARAM_ST.hpp>
#include <param/paramdef/GESTURE_PARAM_ST.hpp>
#include <param/paramdef/GPARAM_GRID_REGION_INFO_PARAM_ST.hpp>
#include <param/paramdef/GPARAM_REF_SETTINGS_PARAM_ST.hpp>
#include <param/paramdef/GRAPHICS_COMMON_PARAM_ST.hpp>
#include <param/paramdef/GRASS_LOD_RANGE_PARAM_ST.hpp>
#include <param/paramdef/GRASS_MAP_SETTINGS_PARAM_ST.hpp>
#include <param/paramdef/GRASS_TYPE_PARAM_ST.hpp>
#include <param/paramdef/HIT_EFFECT_SE_PARAM_ST.hpp>
#include <param/paramdef/HIT_EFFECT_SFX_CONCEPT_PARAM_ST.hpp>
#include <param/paramdef/HIT_EFFECT_SFX_PARAM_ST.hpp>
#include <param/paramdef/HIT_MTRL_PARAM_ST.hpp>
#include <param/paramdef/ITEMLOT_PARAM_ST.hpp>
#include <param/paramdef/KEY_ASSIGN_PARAM_ST.hpp>
#include <param/paramdef/KNOCKBACK_PARAM_ST.hpp>
#include <param/paramdef/KNOWLEDGE_LOADSCREEN_ITEM_PARAM_ST.hpp>
#include <param/paramdef/LEGACY_DISTANT_VIEW_PARTS_REPLACE_PARAM.hpp>
#include <param/paramdef/LOAD_BALANCER_DRAW_DIST_SCALE_PARAM_ST.hpp>
#include <param/paramdef/LOAD_BALANCER_NEW_DRAW_DIST_SCALE_PARAM_ST.hpp>
#include <param/paramdef/LOAD_BALANCER_PARAM_ST.hpp>
#include <param/paramdef/LOCK_CAM_PARAM_ST.hpp>
#include <param/paramdef/MAGIC_PARAM_ST.hpp>
#include <param/paramdef/MAP_DEFAULT_INFO_PARAM_ST.hpp>
#include <param/paramdef/MAP_GD_REGION_DRAW_PARAM.hpp>
#include <param/paramdef/MAP_GD_REGION_ID_PARAM_ST.hpp>
#include <param/paramdef/MAP_GRID_CREATE_HEIGHT_LIMIT_INFO_PARAM_ST.hpp>
#include <param/paramdef/MAP_MIMICRY_ESTABLISHMENT_PARAM_ST.hpp>
#include <param/paramdef/MAP_NAME_TEX_PARAM_ST.hpp>
#include <param/paramdef/MAP_PIECE_TEX_PARAM_ST.hpp>
#include <param/paramdef/MATERIAL_EX_PARAM_ST.hpp>
#include <param/paramdef/MENUPROPERTY_LAYOUT.hpp>
#include <param/paramdef/MENUPROPERTY_SPEC.hpp>
#include <param/paramdef/MENU_COMMON_PARAM_ST.hpp>
#include <param/paramdef/MENU_OFFSCR_REND_PARAM_ST.hpp>
#include <param/paramdef/MENU_PARAM_COLOR_TABLE_ST.hpp>
#include <param/paramdef/MENU_VALUE_TABLE_SPEC.hpp>
#include <param/paramdef/MIMICRY_ESTABLISHMENT_TEX_PARAM_ST.hpp>
#include <param/paramdef/MISSILE_PARAM_ST.hpp>
#include <param/paramdef/MODEL_SFX_PARAM_ST.hpp>
#include <param/paramdef/MOVE_PARAM_ST.hpp>
#include <param/paramdef/MULTI_ESTUS_FLASK_BONUS_PARAM_ST.hpp>
#include <param/paramdef/MULTI_PLAY_CORRECTION_PARAM_ST.hpp>
#include <param/paramdef/MULTI_SOUL_BONUS_RATE_PARAM_ST.hpp>
#include <param/paramdef/NETWORK_AREA_PARAM_ST.hpp>
#include <param/paramdef/NETWORK_MSG_PARAM_ST.hpp>
#include <param/paramdef/NETWORK_PARAM_ST.hpp>
#include <param/paramdef/NPC_AI_ACTION_PARAM_ST.hpp>
#include <param/paramdef/NPC_AI_BEHAVIOR_PROBABILITY_PARAM_ST.hpp>
#include <param/paramdef/NPC_PARAM_ST.hpp>
#include <param/paramdef/NPC_THINK_PARAM_ST.hpp>
#include <param/paramdef/OBJECT_MATERIAL_SFX_PARAM_ST.hpp>
#include <param/paramdef/OBJECT_PARAM_ST.hpp>
#include <param/paramdef/OBJ_ACT_PARAM_ST.hpp>
#include <param/paramdef/PARTS_DRAW_PARAM_ST.hpp>
#include <param/paramdef/PERFORMANCE_CHECK_PARAM.hpp>
#include <param/paramdef/PHANTOM_PARAM_ST.hpp>
#include <param/paramdef/PLAYER_COMMON_PARAM_ST.hpp>
#include <param/paramdef/PLAY_REGION_PARAM_ST.hpp>
#include <param/paramdef/POSTURE_CONTROL_PARAM_GENDER_ST.hpp>
#include <param/paramdef/POSTURE_CONTROL_PARAM_PRO_ST.hpp>
#include <param/paramdef/POSTURE_CONTROL_PARAM_WEP_LEFT_ST.hpp>
#include <param/paramdef/POSTURE_CONTROL_PARAM_WEP_RIGHT_ST.hpp>
#include <param/paramdef/RANDOM_APPEAR_EDIT_PARAM_ST.hpp>
#include <param/paramdef/RANDOM_APPEAR_PARAM_ST.hpp>
#include <param/paramdef/REINFORCE_PARAM_PROTECTOR_ST.hpp>
#include <param/paramdef/REINFORCE_PARAM_WEAPON_ST.hpp>
#include <param/paramdef/RESIST_CORRECT_PARAM_ST.hpp>
#include <param/paramdef/REVERB_AUX_SEND_BUS_PARAM_ST.hpp>
#include <param/paramdef/RIDE_PARAM_ST.hpp>
#include <param/paramdef/ROLE_PARAM_ST.hpp>
#include <param/paramdef/ROLLING_OBJ_LOT_PARAM_ST.hpp>
#include <param/paramdef/RUNTIME_BONE_CONTROL_PARAM_ST.hpp>
#include <param/paramdef/SE_ACTIVATION_RANGE_PARAM_ST.hpp>
#include <param/paramdef/SE_MATERIAL_CONVERT_PARAM_ST.hpp>
#include <param/paramdef/SFX_BLOCK_RES_SHARE_PARAM.hpp>
#include <param/paramdef/SHOP_LINEUP_PARAM.hpp>
#include <param/paramdef/SIGN_PUDDLE_PARAM_ST.hpp>
#include <param/paramdef/SOUND_ASSET_SOUND_OBJ_ENABLE_DIST_PARAM_ST.hpp>
#include <param/paramdef/SOUND_AUTO_ENV_SOUND_GROUP_PARAM_ST.hpp>
#include <param/paramdef/SOUND_AUTO_REVERB_EVALUATION_DIST_PARAM_ST.hpp>
#include <param/paramdef/SOUND_AUTO_REVERB_SELECT_PARAM_ST.hpp>
#include <param/paramdef/SOUND_CHR_PHYSICS_SE_PARAM_ST.hpp>
#include <param/paramdef/SOUND_COMMON_INGAME_PARAM_ST.hpp>
#include <param/paramdef/SOUND_COMMON_SYSTEM_PARAM_ST.hpp>
#include <param/paramdef/SOUND_CUTSCENE_PARAM_ST.hpp>
#include <param/paramdef/SPEEDTREE_MODEL_PARAM_ST.hpp>
#include <param/paramdef/SP_EFFECT_PARAM_ST.hpp>
#include <param/paramdef/SP_EFFECT_SET_PARAM_ST.hpp>
#include <param/paramdef/SP_EFFECT_VFX_PARAM_ST.hpp>
#include <param/paramdef/SWORD_ARTS_PARAM_ST.hpp>
#include <param/paramdef/TALK_PARAM_ST.hpp>
#include <param/paramdef/THROW_DIRECTION_SFX_PARAM_ST.hpp>
#include <param/paramdef/THROW_PARAM_ST.hpp>
#include <param/paramdef/TOUGHNESS_PARAM_ST.hpp>
#include <param/paramdef/TUTORIAL_PARAM_ST.hpp>
#include <param/paramdef/WAYPOINT_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_ASSET_CREATE_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_ASSET_REPLACE_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_LOT_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_LOT_TEX_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_PARAM_ST.hpp>
#include <param/paramdef/WEP_ABSORP_POS_PARAM_ST.hpp>
#include <param/paramdef/WET_ASPECT_PARAM_ST.hpp>
#include <param/paramdef/WHITE_SIGN_COOL_TIME_PARAM_ST.hpp>
#include <param/paramdef/WORLD_MAP_LEGACY_CONV_PARAM_ST.hpp>
#include <param/paramdef/WORLD_MAP_PIECE_PARAM_ST.hpp>
#include <param/paramdef/WORLD_MAP_PLACE_NAME_PARAM_ST.hpp>
#include <param/paramdef/WORLD_MAP_POINT_PARAM_ST.hpp>
#include <param/paramdef/WWISE_VALUE_TO_STR_CONVERT_PARAM_ST.hpp>
#include <param/paramdef/CHR_EQUIP_MODEL_PARAM_ST.hpp>
#include <param/paramdef/MAP_GRID_CREATE_HEIGHT_LIMIT_DETAIL_INFO_PARAM_ST.hpp>
#include <param/paramdef/MAP_NAME_TEX_PARAM_ST_DLC02.hpp>
#include <param/paramdef/MAP_PIECE_TEX_PARAM_ST_DLC02.hpp>
#include <param/paramdef/MIMICRY_ESTABLISHMENT_TEX_PARAM_ST_DLC02.hpp>
#include <param/paramdef/SIGN_PUDDLE_SUB_CATEGORY_PARAM_ST.hpp>
#include <param/paramdef/SIGN_PUDDLE_TAB_PARAM_ST.hpp>
#include <param/paramdef/WEATHER_LOT_TEX_PARAM_ST_DLC02.hpp>