/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdef {

struct AI_ANIM_TBL_PARAM {
    unsigned short atk0_EzStateId{ 0 };
    unsigned short atk1_EzStateId{ 0 };
    unsigned short atk2_EzStateId{ 0 };
    unsigned short atk3_EzStateId{ 0 };
    unsigned short atk4_EzStateId{ 0 };
    unsigned short atk5_EzStateId{ 0 };
    unsigned short atk6_EzStateId{ 0 };
    unsigned short atk7_EzStateId{ 0 };
    unsigned short atk8_EzStateId{ 0 };
    unsigned short atk9_EzStateId{ 0 };
    unsigned short atk10_EzStateId{ 0 };
    unsigned short atk11_EzStateId{ 0 };
    unsigned short atk12_EzStateId{ 0 };
    unsigned short atk13_EzStateId{ 0 };
    unsigned short atk14_EzStateId{ 0 };
    unsigned short atk15_EzStateId{ 0 };
    unsigned short atk16_EzStateId{ 0 };
    unsigned short atk17_EzStateId{ 0 };
    unsigned short atk18_EzStateId{ 0 };
    unsigned short atk19_EzStateId{ 0 };
    unsigned short atk20_EzStateId{ 0 };
    unsigned short atk21_EzStateId{ 0 };
    unsigned short atk22_EzStateId{ 0 };
    unsigned short atk23_EzStateId{ 0 };
    unsigned short atk24_EzStateId{ 0 };
    unsigned short atk25_EzStateId{ 0 };
    unsigned short atk26_EzStateId{ 0 };
    unsigned short atk27_EzStateId{ 0 };
    unsigned short atk28_EzStateId{ 0 };
    unsigned short atk29_EzStateId{ 0 };
    unsigned short atk0_MinDist{ 0 };
    unsigned short atk1_MinDist{ 0 };
    unsigned short atk2_MinDist{ 0 };
    unsigned short atk3_MinDist{ 0 };
    unsigned short atk4_MinDist{ 0 };
    unsigned short atk5_MinDist{ 0 };
    unsigned short atk6_MinDist{ 0 };
    unsigned short atk7_MinDist{ 0 };
    unsigned short atk8_MinDist{ 0 };
    unsigned short atk9_MinDist{ 0 };
    unsigned short atk10_MinDist{ 0 };
    unsigned short atk11_MinDist{ 0 };
    unsigned short atk12_MinDist{ 0 };
    unsigned short atk13_MinDist{ 0 };
    unsigned short atk14_MinDist{ 0 };
    unsigned short atk15_MinDist{ 0 };
    unsigned short atk16_MinDist{ 0 };
    unsigned short atk17_MinDist{ 0 };
    unsigned short atk18_MinDist{ 0 };
    unsigned short atk19_MinDist{ 0 };
    unsigned short atk20_MinDist{ 0 };
    unsigned short atk21_MinDist{ 0 };
    unsigned short atk22_MinDist{ 0 };
    unsigned short atk23_MinDist{ 0 };
    unsigned short atk24_MinDist{ 0 };
    unsigned short atk25_MinDist{ 0 };
    unsigned short atk26_MinDist{ 0 };
    unsigned short atk27_MinDist{ 0 };
    unsigned short atk28_MinDist{ 0 };
    unsigned short atk29_MinDist{ 0 };
    unsigned short atk0_MaxDist{ 0 };
    unsigned short atk1_MaxDist{ 0 };
    unsigned short atk2_MaxDist{ 0 };
    unsigned short atk3_MaxDist{ 0 };
    unsigned short atk4_MaxDist{ 0 };
    unsigned short atk5_MaxDist{ 0 };
    unsigned short atk6_MaxDist{ 0 };
    unsigned short atk7_MaxDist{ 0 };
    unsigned short atk8_MaxDist{ 0 };
    unsigned short atk9_MaxDist{ 0 };
    unsigned short atk10_MaxDist{ 0 };
    unsigned short atk11_MaxDist{ 0 };
    unsigned short atk12_MaxDist{ 0 };
    unsigned short atk13_MaxDist{ 0 };
    unsigned short atk14_MaxDist{ 0 };
    unsigned short atk15_MaxDist{ 0 };
    unsigned short atk16_MaxDist{ 0 };
    unsigned short atk17_MaxDist{ 0 };
    unsigned short atk18_MaxDist{ 0 };
    unsigned short atk19_MaxDist{ 0 };
    unsigned short atk20_MaxDist{ 0 };
    unsigned short atk21_MaxDist{ 0 };
    unsigned short atk22_MaxDist{ 0 };
    unsigned short atk23_MaxDist{ 0 };
    unsigned short atk24_MaxDist{ 0 };
    unsigned short atk25_MaxDist{ 0 };
    unsigned short atk26_MaxDist{ 0 };
    unsigned short atk27_MaxDist{ 0 };
    unsigned short atk28_MaxDist{ 0 };
    unsigned short atk29_MaxDist{ 0 };
    unsigned char atk0_AtkDistType : 4 { 0 };
    unsigned char atk1_AtkDistType : 4 { 0 };
    unsigned char atk2_AtkDistType : 4 { 0 };
    unsigned char atk3_AtkDistType : 4 { 0 };
    unsigned char atk4_AtkDistType : 4 { 0 };
    unsigned char atk5_AtkDistType : 4 { 0 };
    unsigned char atk6_AtkDistType : 4 { 0 };
    unsigned char atk7_AtkDistType : 4 { 0 };
    unsigned char atk8_AtkDistType : 4 { 0 };
    unsigned char atk9_AtkDistType : 4 { 0 };
    unsigned char atk10_AtkDistType : 4 { 0 };
    unsigned char atk11_AtkDistType : 4 { 0 };
    unsigned char atk12_AtkDistType : 4 { 0 };
    unsigned char atk13_AtkDistType : 4 { 0 };
    unsigned char atk14_AtkDistType : 4 { 0 };
    unsigned char atk15_AtkDistType : 4 { 0 };
    unsigned char atk16_AtkDistType : 4 { 0 };
    unsigned char atk17_AtkDistType : 4 { 0 };
    unsigned char atk18_AtkDistType : 4 { 0 };
    unsigned char atk19_AtkDistType : 4 { 0 };
    unsigned char atk20_AtkDistType : 4 { 0 };
    unsigned char atk21_AtkDistType : 4 { 0 };
    unsigned char atk22_AtkDistType : 4 { 0 };
    unsigned char atk23_AtkDistType : 4 { 0 };
    unsigned char atk24_AtkDistType : 4 { 0 };
    unsigned char atk25_AtkDistType : 4 { 0 };
    unsigned char atk26_AtkDistType : 4 { 0 };
    unsigned char atk27_AtkDistType : 4 { 0 };
    unsigned char atk28_AtkDistType : 4 { 0 };
    unsigned char atk29_AtkDistType : 4 { 0 };
    unsigned char pad0[13];
};

}; // namespace paramdef
}; // namespace from
