/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdef {

struct AI_ODDS_PARAM {
    unsigned char act0{ 0 };
    unsigned char act1{ 0 };
    unsigned char act2{ 0 };
    unsigned char act3{ 0 };
    unsigned char act4{ 0 };
    unsigned char act5{ 0 };
    unsigned char act6{ 0 };
    unsigned char act7{ 0 };
    unsigned char act8{ 0 };
    unsigned char act9{ 0 };
    unsigned char act10{ 0 };
    unsigned char act11{ 0 };
    unsigned char act12{ 0 };
    unsigned char act13{ 0 };
    unsigned char act14{ 0 };
    unsigned char act15{ 0 };
    unsigned char act16{ 0 };
    unsigned char act17{ 0 };
    unsigned char act18{ 0 };
    unsigned char act19{ 0 };
    unsigned char act20{ 0 };
    unsigned char act21{ 0 };
    unsigned char act22{ 0 };
    unsigned char act23{ 0 };
    unsigned char act24{ 0 };
    unsigned char act25{ 0 };
    unsigned char act26{ 0 };
    unsigned char act27{ 0 };
    unsigned char act28{ 0 };
    unsigned char act29{ 0 };
    unsigned char act30{ 0 };
    unsigned char act31{ 0 };
    unsigned char act32{ 0 };
    unsigned char act33{ 0 };
    unsigned char act34{ 0 };
    unsigned char act35{ 0 };
    unsigned char act36{ 0 };
    unsigned char act37{ 0 };
    unsigned char act38{ 0 };
    unsigned char act39{ 0 };
    unsigned char act40{ 0 };
    unsigned char act41{ 0 };
    unsigned char act42{ 0 };
    unsigned char act43{ 0 };
    unsigned char act44{ 0 };
    unsigned char act45{ 0 };
    unsigned char act46{ 0 };
    unsigned char act47{ 0 };
    unsigned char act48{ 0 };
    unsigned char act49{ 0 };
    unsigned char act50{ 0 };
    unsigned char act51{ 0 };
    unsigned char act52{ 0 };
    unsigned char act53{ 0 };
    unsigned char act54{ 0 };
    unsigned char act55{ 0 };
    unsigned char act56{ 0 };
    unsigned char act57{ 0 };
    unsigned char act58{ 0 };
    unsigned char act59{ 0 };
    unsigned char act60{ 0 };
    unsigned char act61{ 0 };
    unsigned char act62{ 0 };
    unsigned char act63{ 0 };
    unsigned char act64{ 0 };
    unsigned char act65{ 0 };
    unsigned char act66{ 0 };
    unsigned char act67{ 0 };
    unsigned char act68{ 0 };
    unsigned char act69{ 0 };
    unsigned char act70{ 0 };
    unsigned char act71{ 0 };
    unsigned char act72{ 0 };
    unsigned char act73{ 0 };
    unsigned char act74{ 0 };
    unsigned char act75{ 0 };
    unsigned char act76{ 0 };
    unsigned char act77{ 0 };
    unsigned char act78{ 0 };
    unsigned char act79{ 0 };
    unsigned char act80{ 0 };
    unsigned char act81{ 0 };
    unsigned char act82{ 0 };
    unsigned char act83{ 0 };
    unsigned char act84{ 0 };
    unsigned char act85{ 0 };
    unsigned char act86{ 0 };
    unsigned char act87{ 0 };
    unsigned char act88{ 0 };
    unsigned char act89{ 0 };
    unsigned char act90{ 0 };
    unsigned char act91{ 0 };
    unsigned char act92{ 0 };
    unsigned char act93{ 0 };
    unsigned char act94{ 0 };
    unsigned char act95{ 0 };
    unsigned char act96{ 0 };
    unsigned char act97{ 0 };
    unsigned char act98{ 0 };
    unsigned char act99{ 0 };
    unsigned char pad0[12];
};

}; // namespace paramdef
}; // namespace from
