/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdefs {

struct SP_EFFECT_PARAM_ST {
    int iconId{ -1 };
    float conditionHp{ -1 };
    float effectEndurance{ 0 };
    float motionInterval{ 0 };
    float maxHpRate{ 1 };
    float maxMpRate{ 1 };
    float maxStaminaRate{ 1 };
    float slashDamageCutRate{ 1 };
    float blowDamageCutRate{ 1 };
    float thrustDamageCutRate{ 1 };
    float neutralDamageCutRate{ 1 };
    float magicDamageCutRate{ 1 };
    float fireDamageCutRate{ 1 };
    float thunderDamageCutRate{ 1 };
    float physicsAttackRate{ 1 };
    float magicAttackRate{ 1 };
    float fireAttackRate{ 1 };
    float thunderAttackRate{ 1 };
    float physicsAttackPowerRate{ 1 };
    float magicAttackPowerRate{ 1 };
    float fireAttackPowerRate{ 1 };
    float thunderAttackPowerRate{ 1 };
    int physicsAttackPower{ 0 };
    int magicAttackPower{ 0 };
    int fireAttackPower{ 0 };
    int thunderAttackPower{ 0 };
    float physicsDiffenceRate{ 1 };
    float magicDiffenceRate{ 1 };
    float fireDiffenceRate{ 1 };
    float thunderDiffenceRate{ 1 };
    int physicsDiffence{ 0 };
    int magicDiffence{ 0 };
    int fireDiffence{ 0 };
    int thunderDiffence{ 0 };
    float NoGuardDamageRate{ 1 };
    float vitalSpotChangeRate{ -1 };
    float normalSpotChangeRate{ -1 };
    float lookAtTargetPosOffset{ 0 };
    int behaviorId{ -1 };
    float changeHpRate{ 0 };
    int changeHpPoint{ 0 };
    float changeMpRate{ 0 };
    int changeMpPoint{ 0 };
    int mpRecoverChangeSpeed{ 0 };
    float changeStaminaRate{ 0 };
    int changeStaminaPoint{ 0 };
    int staminaRecoverChangeSpeed{ 0 };
    float magicEffectTimeChange{ 0 };
    int insideDurability{ 0 };
    int maxDurability{ 0 };
    float staminaAttackRate{ 1 };
    int poizonAttackPower{ 0 };
    int diseaseAttackPower{ 0 };
    int bloodAttackPower{ 0 };
    int curseAttackPower{ 0 };
    float fallDamageRate{ 0 };
    float soulRate{ 0 };
    float equipWeightChangeRate{ 0 };
    float allItemWeightChangeRate{ 0 };
    int soul{ 0 };
    int animIdOffset{ -1 };
    float haveSoulRate{ 1 };
    float targetPriority{ 0 };
    float sightSearchEnemyRate{ 1 };
    float hearingSearchEnemyRate{ 1 };
    float grabityRate{ 1 };
    float registPoizonChangeRate{ 1 };
    float registDiseaseChangeRate{ 1 };
    float registBloodChangeRate{ 1 };
    float registCurseChangeRate{ 1 };
    float soulStealRate{ 0 };
    float lifeReductionRate{ 0 };
    float hpRecoverRate{ 0 };
    int replaceSpEffectId{ -1 };
    int cycleOccurrenceSpEffectId{ -1 };
    int atkOccurrenceSpEffectId{ -1 };
    float guardDefFlickPowerRate{ 1 };
    float guardStaminaCutRate{ 1 };
    short rayCastPassedTime{ -1 };
    unsigned char magicSubCategoryChange1{ 0 };
    unsigned char magicSubCategoryChange2{ 0 };
    short bowDistRate{ 0 };
    unsigned short spCategory{ 0 };
    unsigned char categoryPriority{ 0 };
    signed char saveCategory{ -1 };
    unsigned char changeMagicSlot{ 0 };
    unsigned char changeMiracleSlot{ 0 };
    signed char heroPointDamage{ 0 };
    unsigned char defFlickPower{ 0 };
    unsigned char flickDamageCutRate{ 0 };
    unsigned char bloodDamageRate{ 100 };
    signed char dmgLv_None{ 0 };
    signed char dmgLv_S{ 0 };
    signed char dmgLv_M{ 0 };
    signed char dmgLv_L{ 0 };
    signed char dmgLv_BlowM{ 0 };
    signed char dmgLv_Push{ 0 };
    signed char dmgLv_Strike{ 0 };
    signed char dmgLv_BlowS{ 0 };
    signed char dmgLv_Min{ 0 };
    signed char dmgLv_Uppercut{ 0 };
    signed char dmgLv_BlowLL{ 0 };
    signed char dmgLv_Breath{ 0 };
    unsigned char atkAttribute{ 254 };
    unsigned char spAttribute{ 254 };
    unsigned short stateInfo{ 0 };
    unsigned char wepParamChange{ 0 };
    unsigned char moveType{ 0 };
    unsigned short lifeReductionType{ 0 };
    unsigned char throwCondition{ 0 };
    signed char addBehaviorJudgeId_condition{ -1 };
    unsigned char freezeDamageRate{ 100 };
    bool effectTargetSelf : 1 { false };
    bool effectTargetFriend : 1 { false };
    bool effectTargetEnemy : 1 { false };
    bool effectTargetPlayer : 1 { false };
    bool effectTargetAI : 1 { false };
    bool effectTargetLive : 1 { false };
    bool effectTargetGhost : 1 { false };
    bool disableSleep : 1 { false };
    bool disableMadness : 1 { false };
    bool effectTargetAttacker : 1 { false };
    bool dispIconNonactive : 1 { false };
    bool regainGaugeDamage : 1 { false };
    bool bAdjustMagicAblity : 1 { false };
    bool bAdjustFaithAblity : 1 { false };
    bool bGameClearBonus : 1 { false };
    bool magParamChange : 1 { false };
    bool miracleParamChange : 1 { false };
    bool clearSoul : 1 { false };
    bool requestSOS : 1 { false };
    bool requestBlackSOS : 1 { false };
    bool requestForceJoinBlackSOS : 1 { false };
    bool requestKickSession : 1 { false };
    bool requestLeaveSession : 1 { false };
    bool requestNpcInveda : 1 { false };
    bool noDead : 1 { false };
    bool bCurrHPIndependeMaxHP : 1 { false };
    bool corrosionIgnore : 1 { false };
    bool sightSearchCutIgnore : 1 { false };
    bool hearingSearchCutIgnore : 1 { false };
    bool antiMagicIgnore : 1 { false };
    bool fakeTargetIgnore : 1 { false };
    bool fakeTargetIgnoreUndead : 1 { false };
    bool fakeTargetIgnoreAnimal : 1 { false };
    bool grabityIgnore : 1 { false };
    bool disablePoison : 1 { false };
    bool disableDisease : 1 { false };
    bool disableBlood : 1 { false };
    bool disableCurse : 1 { false };
    bool enableCharm : 1 { false };
    bool enableLifeTime : 1 { false };
    bool bAdjustStrengthAblity : 1 { false };
    bool bAdjustAgilityAblity : 1 { false };
    bool eraseOnBonfireRecover : 1 { false };
    bool throwAttackParamChange : 1 { false };
    bool requestLeaveColiseumSession : 1 { false };
    bool isExtendSpEffectLife : 1 { false };
    bool hasTarget : 1 { false };
    bool replanningOnFire : 1 { false };
    bool vowType0 : 1 { false };
    bool vowType1 : 1 { false };
    bool vowType2 : 1 { false };
    bool vowType3 : 1 { false };
    bool vowType4 : 1 { false };
    bool vowType5 : 1 { false };
    bool vowType6 : 1 { false };
    bool vowType7 : 1 { false };
    bool vowType8 : 1 { false };
    bool vowType9 : 1 { false };
    bool vowType10 : 1 { false };
    bool vowType11 : 1 { false };
    bool vowType12 : 1 { false };
    bool vowType13 : 1 { false };
    bool vowType14 : 1 { false };
    bool vowType15 : 1 { false };
    signed char repAtkDmgLv{ 0 };
    float sightSearchRate{ 1 };
    bool effectTargetOpposeTarget : 1 { false };
    bool effectTargetFriendlyTarget : 1 { false };
    bool effectTargetSelfTarget : 1 { false };
    bool effectTargetPcHorse : 1 { false };
    bool effectTargetPcDeceased : 1 { false };
    bool isContractSpEffectLife : 1 { false };
    bool isWaitModeDelete : 1 { false };
    bool isIgnoreNoDamage : 1 { false };
    signed char changeTeamType{ -1 };
    short dmypolyId{ -1 };
    int vfxId{ -1 };
    int accumuOverFireId{ -1 };
    int accumuOverVal{ -1 };
    int accumuUnderFireId{ -1 };
    int accumuUnderVal{ -1 };
    int accumuVal{ 0 };
    unsigned char eye_angX{ 0 };
    unsigned char eye_angY{ 0 };
    short addDeceasedLv{ 0 };
    int vfxId1{ -1 };
    int vfxId2{ -1 };
    int vfxId3{ -1 };
    int vfxId4{ -1 };
    int vfxId5{ -1 };
    int vfxId6{ -1 };
    int vfxId7{ -1 };
    int freezeAttackPower{ 0 };
    int AppearAiSoundId{ 0 };
    short addFootEffectSfxId{ -1 };
    signed char dexterityCancelSystemOnlyAddDexterity{ 0 };
    signed char teamOffenseEffectivity{ -1 };
    float toughnessDamageCutRate{ 1 };
    float weakDmgRateA{ 1 };
    float weakDmgRateB{ 1 };
    float weakDmgRateC{ 1 };
    float weakDmgRateD{ 1 };
    float weakDmgRateE{ 1 };
    float weakDmgRateF{ 1 };
    float darkDamageCutRate{ 1 };
    float darkDiffenceRate{ 1 };
    int darkDiffence{ 0 };
    float darkAttackRate{ 1 };
    float darkAttackPowerRate{ 1 };
    int darkAttackPower{ 0 };
    float antiDarkSightRadius{ 0 };
    int antiDarkSightDmypolyId{ -1 };
    float conditionHpRate{ -1 };
    float consumeStaminaRate{ 1 };
    float itemDropRate{ 0 };
    int changePoisonResistPoint{ 0 };
    int changeDiseaseResistPoint{ 0 };
    int changeBloodResistPoint{ 0 };
    int changeCurseResistPoint{ 0 };
    int changeFreezeResistPoint{ 0 };
    float slashAttackRate{ 1 };
    float blowAttackRate{ 1 };
    float thrustAttackRate{ 1 };
    float neutralAttackRate{ 1 };
    float slashAttackPowerRate{ 1 };
    float blowAttackPowerRate{ 1 };
    float thrustAttackPowerRate{ 1 };
    float neutralAttackPowerRate{ 1 };
    int slashAttackPower{ 0 };
    int blowAttackPower{ 0 };
    int thrustAttackPower{ 0 };
    int neutralAttackPower{ 0 };
    int changeStrengthPoint{ 0 };
    int changeAgilityPoint{ 0 };
    int changeMagicPoint{ 0 };
    int changeFaithPoint{ 0 };
    int changeLuckPoint{ 0 };
    signed char recoverArtsPoint_Str{ 0 };
    signed char recoverArtsPoint_Dex{ 0 };
    signed char recoverArtsPoint_Magic{ 0 };
    signed char recoverArtsPoint_Miracle{ 0 };
    unsigned char madnessDamageRate{ 100 };
    bool isUseStatusAilmentAtkPowerCorrect : 1 { false };
    bool isUseAtkParamAtkPowerCorrect : 1 { false };
    bool dontDeleteOnDead : 1 { false };
    bool disableFreeze : 1 { false };
    bool isDisableNetSync : 1 { false };
    bool shamanParamChange : 1 { false };
    bool isStopSearchedNotify : 1 { false };
    bool isCheckAboveShadowTest : 1 { false };
    unsigned short addBehaviorJudgeId_add{ 0 };
    float saReceiveDamageRate{ 1 };
    float defPlayerDmgCorrectRate_Physics{ 1 };
    float defPlayerDmgCorrectRate_Magic{ 1 };
    float defPlayerDmgCorrectRate_Fire{ 1 };
    float defPlayerDmgCorrectRate_Thunder{ 1 };
    float defPlayerDmgCorrectRate_Dark{ 1 };
    float defEnemyDmgCorrectRate_Physics{ 1 };
    float defEnemyDmgCorrectRate_Magic{ 1 };
    float defEnemyDmgCorrectRate_Fire{ 1 };
    float defEnemyDmgCorrectRate_Thunder{ 1 };
    float defEnemyDmgCorrectRate_Dark{ 1 };
    float defObjDmgCorrectRate{ 1 };
    float atkPlayerDmgCorrectRate_Physics{ 1 };
    float atkPlayerDmgCorrectRate_Magic{ 1 };
    float atkPlayerDmgCorrectRate_Fire{ 1 };
    float atkPlayerDmgCorrectRate_Thunder{ 1 };
    float atkPlayerDmgCorrectRate_Dark{ 1 };
    float atkEnemyDmgCorrectRate_Physics{ 1 };
    float atkEnemyDmgCorrectRate_Magic{ 1 };
    float atkEnemyDmgCorrectRate_Fire{ 1 };
    float atkEnemyDmgCorrectRate_Thunder{ 1 };
    float atkEnemyDmgCorrectRate_Dark{ 1 };
    float registFreezeChangeRate{ 1 };
    unsigned short invocationConditionsStateChange1{ 0 };
    unsigned short invocationConditionsStateChange2{ 0 };
    unsigned short invocationConditionsStateChange3{ 0 };
    short hearingAiSoundLevel{ -1 };
    float chrProxyHeightRate{ 1 };
    float addAwarePointCorrectValue_forMe{ 0 };
    float addAwarePointCorrectValue_forTarget{ 0 };
    float sightSearchEnemyAdd{ 0 };
    float sightSearchAdd{ 0 };
    float hearingSearchAdd{ 0 };
    float hearingSearchRate{ 1 };
    float hearingSearchEnemyAdd{ 0 };
    float value_Magnification{ 1 };
    float artsConsumptionRate{ 1 };
    float magicConsumptionRate{ 1 };
    float shamanConsumptionRate{ 1 };
    float miracleConsumptionRate{ 1 };
    int changeHpEstusFlaskRate{ 0 };
    int changeHpEstusFlaskPoint{ 0 };
    int changeMpEstusFlaskRate{ 0 };
    int changeMpEstusFlaskPoint{ 0 };
    float changeHpEstusFlaskCorrectRate{ 1 };
    float changeMpEstusFlaskCorrectRate{ 1 };
    int applyIdOnGetSoul{ 0 };
    float extendLifeRate{ 1 };
    float contractLifeRate{ 1 };
    float defObjectAttackPowerRate{ 1 };
    short effectEndDeleteDecalGroupId{ -1 };
    signed char addLifeForceStatus{ 0 };
    signed char addWillpowerStatus{ 0 };
    signed char addEndureStatus{ 0 };
    signed char addVitalityStatus{ 0 };
    signed char addStrengthStatus{ 0 };
    signed char addDexterityStatus{ 0 };
    signed char addMagicStatus{ 0 };
    signed char addFaithStatus{ 0 };
    signed char addLuckStatus{ 0 };
    unsigned char deleteCriteriaDamage{ 0 };
    unsigned char magicSubCategoryChange3{ 0 };
    unsigned char spAttributeVariationValue{ 0 };
    unsigned char atkFlickPower{ 0 };
    unsigned char wetConditionDepth{ 0 };
    float changeSaRecoveryVelocity{ 1 };
    float regainRate{ 1 };
    float saAttackPowerRate{ 1 };
    int sleepAttackPower{ 0 };
    int madnessAttackPower{ 0 };
    float registSleepChangeRate{ 1 };
    float registMadnessChangeRate{ 1 };
    int changeSleepResistPoint{ 0 };
    int changeMadnessResistPoint{ 0 };
    unsigned char sleepDamageRate{ 100 };
    unsigned char applyPartsGroup{ 0 };
    bool clearTarget : 1 { false };
    bool fakeTargetIgnoreAjin : 1 { false };
    bool fakeTargetIgnoreMirageArts : 1 { false };
    bool requestForceJoinBlackSOS_B : 1 { false };
    bool isDestinedDeathHpMult : 1 { false };
    unsigned char pad2[1];
    float changeSuperArmorPoint{ 0 };
    float changeSaPoint{ 0 };
    float hugeEnemyPickupHeightOverwrite{ 0 };
    float poisonDefDamageRate{ 1 };
    float diseaseDefDamageRate{ 1 };
    float bloodDefDamageRate{ 1 };
    float curseDefDamageRate{ 1 };
    float freezeDefDamageRate{ 1 };
    float sleepDefDamageRate{ 1 };
    float madnessDefDamageRate{ 1 };
    unsigned short overwrite_maxBackhomeDist{ 0 };
    unsigned short overwrite_backhomeDist{ 0 };
    unsigned short overwrite_backhomeBattleDist{ 0 };
    unsigned short overwrite_BackHome_LookTargetDist{ 0 };
    float goodsConsumptionRate{ 1 };
    float guardStaminaMult{ 1 };
    unsigned char unk3[4];
};

}; // namespace paramdefs
}; // namespace from

static_assert(sizeof(from::paramdefs::SP_EFFECT_PARAM_ST) == 912,
    "SP_EFFECT_PARAM_ST paramdef size does not match detected size");
