/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdefs {

struct ATK_PARAM_ST {
    float hit0_Radius{ 0 };
    float hit1_Radius{ 0 };
    float hit2_Radius{ 0 };
    float hit3_Radius{ 0 };
    float knockbackDist{ 0 };
    float hitStopTime{ 0 };
    int spEffectId0{ -1 };
    int spEffectId1{ -1 };
    int spEffectId2{ -1 };
    int spEffectId3{ -1 };
    int spEffectId4{ -1 };
    short hit0_DmyPoly1{ 0 };
    short hit1_DmyPoly1{ 0 };
    short hit2_DmyPoly1{ 0 };
    short hit3_DmyPoly1{ 0 };
    short hit0_DmyPoly2{ 0 };
    short hit1_DmyPoly2{ 0 };
    short hit2_DmyPoly2{ 0 };
    short hit3_DmyPoly2{ 0 };
    unsigned short blowingCorrection{ 0 };
    unsigned short atkPhysCorrection{ 0 };
    unsigned short atkMagCorrection{ 0 };
    unsigned short atkFireCorrection{ 0 };
    unsigned short atkThunCorrection{ 0 };
    unsigned short atkStamCorrection{ 0 };
    unsigned short guardAtkRateCorrection{ 0 };
    unsigned short guardBreakCorrection{ 0 };
    unsigned short atkThrowEscapeCorrection{ 0 };
    unsigned char subCategory1{ 0 };
    unsigned char subCategory2{ 0 };
    unsigned short atkPhys{ 0 };
    unsigned short atkMag{ 0 };
    unsigned short atkFire{ 0 };
    unsigned short atkThun{ 0 };
    unsigned short atkStam{ 0 };
    unsigned short guardAtkRate{ 0 };
    unsigned short guardBreakRate{ 0 };
    unsigned char pad6[1];
    bool isEnableCalcDamageForBushesObj{ false };
    unsigned short atkThrowEscape{ 0 };
    unsigned short atkObj{ 0 };
    short guardStaminaCutRate{ 0 };
    short guardRate{ 0 };
    unsigned short throwTypeId{ 0 };
    unsigned char hit0_hitType{ 0 };
    unsigned char hit1_hitType{ 0 };
    unsigned char hit2_hitType{ 0 };
    unsigned char hit3_hitType{ 0 };
    unsigned char hti0_Priority{ 0 };
    unsigned char hti1_Priority{ 0 };
    unsigned char hti2_Priority{ 0 };
    unsigned char hti3_Priority{ 0 };
    unsigned char dmgLevel{ 0 };
    unsigned char mapHitType{ 0 };
    signed char guardCutCancelRate{ 0 };
    unsigned char atkAttribute{ 0 };
    unsigned char spAttribute{ 0 };
    unsigned char atkType{ 0 };
    unsigned char atkMaterial{ 0 };
    unsigned char guardRangeType{ 0 };
    unsigned short defSeMaterial1{ 0 };
    unsigned char hitSourceType{ 0 };
    unsigned char throwFlag{ 0 };
    bool disableGuard : 1 { false };
    bool disableStaminaAttack : 1 { false };
    bool disableHitSpEffect : 1 { false };
    bool IgnoreNotifyMissSwingForAI : 1 { false };
    bool repeatHitSfx : 1 { false };
    bool isArrowAtk : 1 { false };
    bool isGhostAtk : 1 { false };
    bool isDisableNoDamage : 1 { false };
    signed char atkPow_forSfx{ 0 };
    signed char atkDir_forSfx{ 0 };
    bool opposeTarget : 1 { true };
    bool friendlyTarget : 1 { false };
    bool selfTarget : 1 { false };
    bool isCheckDoorPenetration : 1 { false };
    bool isVsRideAtk : 1 { false };
    bool isAddBaseAtk : 1 { false };
    bool excludeThreatLvNotify : 1 { false };
    unsigned char pad1 : 1;
    unsigned char atkBehaviorId{ 0 };
    signed char atkPow_forSe{ 0 };
    float atkSuperArmor{ 0 };
    int decalId1{ -1 };
    int decalId2{ -1 };
    int AppearAiSoundId{ 0 };
    int HitAiSoundId{ 0 };
    int HitRumbleId{ -1 };
    int HitRumbleIdByNormal{ -1 };
    int HitRumbleIdByMiddle{ -1 };
    int HitRumbleIdByRoot{ -1 };
    int traceSfxId0{ -1 };
    int traceDmyIdHead0{ -1 };
    int traceDmyIdTail0{ -1 };
    int traceSfxId1{ -1 };
    int traceDmyIdHead1{ -1 };
    int traceDmyIdTail1{ -1 };
    int traceSfxId2{ -1 };
    int traceDmyIdHead2{ -1 };
    int traceDmyIdTail2{ -1 };
    int traceSfxId3{ -1 };
    int traceDmyIdHead3{ -1 };
    int traceDmyIdTail3{ -1 };
    int traceSfxId4{ -1 };
    int traceDmyIdHead4{ -1 };
    int traceDmyIdTail4{ -1 };
    int traceSfxId5{ -1 };
    int traceDmyIdHead5{ -1 };
    int traceDmyIdTail5{ -1 };
    int traceSfxId6{ -1 };
    int traceDmyIdHead6{ -1 };
    int traceDmyIdTail6{ -1 };
    int traceSfxId7{ -1 };
    int traceDmyIdHead7{ -1 };
    int traceDmyIdTail7{ -1 };
    float hit4_Radius{ 0 };
    float hit5_Radius{ 0 };
    float hit6_Radius{ 0 };
    float hit7_Radius{ 0 };
    float hit8_Radius{ 0 };
    float hit9_Radius{ 0 };
    float hit10_Radius{ 0 };
    float hit11_Radius{ 0 };
    float hit12_Radius{ 0 };
    float hit13_Radius{ 0 };
    float hit14_Radius{ 0 };
    float hit15_Radius{ 0 };
    short hit4_DmyPoly1{ 0 };
    short hit5_DmyPoly1{ 0 };
    short hit6_DmyPoly1{ 0 };
    short hit7_DmyPoly1{ 0 };
    short hit8_DmyPoly1{ 0 };
    short hit9_DmyPoly1{ 0 };
    short hit10_DmyPoly1{ 0 };
    short hit11_DmyPoly1{ 0 };
    short hit12_DmyPoly1{ 0 };
    short hit13_DmyPoly1{ 0 };
    short hit14_DmyPoly1{ 0 };
    short hit15_DmyPoly1{ 0 };
    short hit4_DmyPoly2{ 0 };
    short hit5_DmyPoly2{ 0 };
    short hit6_DmyPoly2{ 0 };
    short hit7_DmyPoly2{ 0 };
    short hit8_DmyPoly2{ 0 };
    short hit9_DmyPoly2{ 0 };
    short hit10_DmyPoly2{ 0 };
    short hit11_DmyPoly2{ 0 };
    short hit12_DmyPoly2{ 0 };
    short hit13_DmyPoly2{ 0 };
    short hit14_DmyPoly2{ 0 };
    short hit15_DmyPoly2{ 0 };
    unsigned char hit4_hitType{ 0 };
    unsigned char hit5_hitType{ 0 };
    unsigned char hit6_hitType{ 0 };
    unsigned char hit7_hitType{ 0 };
    unsigned char hit8_hitType{ 0 };
    unsigned char hit9_hitType{ 0 };
    unsigned char hit10_hitType{ 0 };
    unsigned char hit11_hitType{ 0 };
    unsigned char hit12_hitType{ 0 };
    unsigned char hit13_hitType{ 0 };
    unsigned char hit14_hitType{ 0 };
    unsigned char hit15_hitType{ 0 };
    unsigned char hti4_Priority{ 0 };
    unsigned char hti5_Priority{ 0 };
    unsigned char hti6_Priority{ 0 };
    unsigned char hti7_Priority{ 0 };
    unsigned char hti8_Priority{ 0 };
    unsigned char hti9_Priority{ 0 };
    unsigned char hti10_Priority{ 0 };
    unsigned char hti11_Priority{ 0 };
    unsigned char hti12_Priority{ 0 };
    unsigned char hti13_Priority{ 0 };
    unsigned char hti14_Priority{ 0 };
    unsigned char hti15_Priority{ 0 };
    unsigned short defSfxMaterial1{ 0 };
    unsigned short defSeMaterial2{ 0 };
    unsigned short defSfxMaterial2{ 0 };
    unsigned short atkDarkCorrection{ 0 };
    unsigned short atkDark{ 0 };
    unsigned char pad5 : 1;
    bool isDisableParry : 1 { true };
    bool isDisableBothHandsAtkBonus : 1 { false };
    bool isInvalidatedByNoDamageInAir : 1 { false };
    unsigned char pad2 : 4;
    signed char dmgLevel_vsPlayer{ 0 };
    unsigned short statusAilmentAtkPowerCorrectRate{ 100 };
    unsigned short spEffectAtkPowerCorrectRate_byPoint{ 100 };
    unsigned short spEffectAtkPowerCorrectRate_byRate{ 100 };
    unsigned short spEffectAtkPowerCorrectRate_byDmg{ 100 };
    unsigned char atkBehaviorId_2{ 0 };
    unsigned char throwDamageAttribute{ 0 };
    unsigned short statusAilmentAtkPowerCorrectRate_byPoint{ 100 };
    int overwriteAttackElementCorrectId{ -1 };
    short decalBaseId1{ -1 };
    short decalBaseId2{ -1 };
    unsigned short wepRegainHpScale{ 100 };
    unsigned short atkRegainHp{ 0 };
    float regainableTimeScale{ 1 };
    float regainableHpRateScale{ 1 };
    signed char regainableSlotId{ -1 };
    unsigned char spAttributeVariationValue{ 0 };
    short parryForwardOffset{ 0 };
    float atkSuperArmorCorrection{ 0 };
    unsigned char defSfxMaterialVariationValue{ 0 };
    unsigned char pad4[3];
    int finalDamageRateId{ 0 };
    unsigned char pad7[12];
};

}; // namespace paramdefs
}; // namespace from

static_assert(sizeof(from::paramdefs::ATK_PARAM_ST) == 456,
    "ATK_PARAM_ST paramdef size does not match detected size");
