/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdefs {

struct DEFAULT_KEY_ASSIGN {
    bool priority0 : 1 { false };
    bool priority1 : 1 { false };
    bool priority2 : 1 { false };
    bool priority3 : 1 { false };
    bool priority4 : 1 { false };
    bool priority5 : 1 { false };
    bool priority6 : 1 { false };
    bool priority7 : 1 { false };
    bool priority8 : 1 { false };
    bool priority9 : 1 { false };
    bool priority10 : 1 { false };
    bool priority11 : 1 { false };
    bool priority12 : 1 { false };
    bool priority13 : 1 { false };
    bool priority14 : 1 { false };
    bool priority15 : 1 { false };
    bool priority16 : 1 { false };
    bool priority17 : 1 { false };
    bool priority18 : 1 { false };
    bool priority19 : 1 { false };
    bool priority20 : 1 { false };
    bool priority21 : 1 { false };
    bool priority22 : 1 { false };
    bool priority23 : 1 { false };
    bool priority24 : 1 { false };
    bool priority25 : 1 { false };
    bool priority26 : 1 { false };
    bool priority27 : 1 { false };
    bool priority28 : 1 { false };
    bool priority29 : 1 { false };
    bool priority30 : 1 { false };
    bool priority31 : 1 { false };
    unsigned char dummy[12];
    int phyisicalKey_0{ -1 };
    unsigned char traitsType_0{ 0 };
    unsigned char a2dOperator_0{ 0 };
    unsigned char applyTarget_0{ 0 };
    bool isAnalog_0 : 1 { false };
    bool enableWin64_0 : 1 { true };
    bool enablePS4_0 : 1 { true };
    bool enableXboxOne_0 : 1 { true };
    float time1_0{ 0 };
    float time2_0{ 0 };
    float a2dThreshold_0{ 0.5 };
    int phyisicalKey_1{ -1 };
    unsigned char traitsType_1{ 0 };
    unsigned char a2dOperator_1{ 0 };
    unsigned char applyTarget_1{ 0 };
    bool isAnalog_1 : 1 { false };
    bool enableWin64_1 : 1 { true };
    bool enablePS4_1 : 1 { true };
    bool enableXboxOne_1 : 1 { true };
    float time1_1{ 0 };
    float time2_1{ 0 };
    float a2dThreshold_1{ 0.5 };
    int phyisicalKey_2{ -1 };
    unsigned char traitsType_2{ 0 };
    unsigned char a2dOperator_2{ 0 };
    unsigned char applyTarget_2{ 0 };
    bool isAnalog_2 : 1 { false };
    bool enableWin64_2 : 1 { true };
    bool enablePS4_2 : 1 { true };
    bool enableXboxOne_2 : 1 { true };
    float time1_2{ 0 };
    float time2_2{ 0 };
    float a2dThreshold_2{ 0.5 };
    int phyisicalKey_3{ -1 };
    unsigned char traitsType_3{ 0 };
    unsigned char a2dOperator_3{ 0 };
    unsigned char applyTarget_3{ 0 };
    bool isAnalog_3 : 1 { false };
    bool enableWin64_3 : 1 { true };
    bool enablePS4_3 : 1 { true };
    bool enableXboxOne_3 : 1 { true };
    float time1_3{ 0 };
    float time2_3{ 0 };
    float a2dThreshold_3{ 0.5 };
    int phyisicalKey_4{ -1 };
    unsigned char traitsType_4{ 0 };
    unsigned char a2dOperator_4{ 0 };
    unsigned char applyTarget_4{ 0 };
    bool isAnalog_4 : 1 { false };
    bool enableWin64_4 : 1 { true };
    bool enablePS4_4 : 1 { true };
    bool enableXboxOne_4 : 1 { true };
    float time1_4{ 0 };
    float time2_4{ 0 };
    float a2dThreshold_4{ 0.5 };
    int phyisicalKey_5{ -1 };
    unsigned char traitsType_5{ 0 };
    unsigned char a2dOperator_5{ 0 };
    unsigned char applyTarget_5{ 0 };
    bool isAnalog_5 : 1 { false };
    bool enableWin64_5 : 1 { true };
    bool enablePS4_5 : 1 { true };
    bool enableXboxOne_5 : 1 { true };
    float time1_5{ 0 };
    float time2_5{ 0 };
    float a2dThreshold_5{ 0.5 };
    int phyisicalKey_6{ -1 };
    unsigned char traitsType_6{ 0 };
    unsigned char a2dOperator_6{ 0 };
    unsigned char applyTarget_6{ 0 };
    bool isAnalog_6 : 1 { false };
    bool enableWin64_6 : 1 { true };
    bool enablePS4_6 : 1 { true };
    bool enableXboxOne_6 : 1 { true };
    float time1_6{ 0 };
    float time2_6{ 0 };
    float a2dThreshold_6{ 0.5 };
    int phyisicalKey_7{ -1 };
    unsigned char traitsType_7{ 0 };
    unsigned char a2dOperator_7{ 0 };
    unsigned char applyTarget_7{ 0 };
    bool isAnalog_7 : 1 { false };
    bool enableWin64_7 : 1 { true };
    bool enablePS4_7 : 1 { true };
    bool enableXboxOne_7 : 1 { true };
    float time1_7{ 0 };
    float time2_7{ 0 };
    float a2dThreshold_7{ 0.5 };
};

}; // namespace paramdefs
}; // namespace from
