/* This file was automatically generated from XML paramdefs. */
#pragma once

namespace from {
namespace paramdefs {

struct EQUIP_PARAM_PROTECTOR_ST {
    bool disableParam_NT : 1 { false };
    unsigned char disableParamReserve1 : 7;
    unsigned char disableParamReserve2[3];
    int sortId{ 0 };
    unsigned int wanderingEquipId{ 0 };
    unsigned short resistSleep{ 0 };
    unsigned short resistMadness{ 0 };
    float saDurability{ 0 };
    float toughnessCorrectRate{ 0 };
    int fixPrice{ 0 };
    int basicPrice{ 0 };
    int sellValue{ 0 };
    float weight{ 1 };
    int residentSpEffectId{ 0 };
    int residentSpEffectId2{ 0 };
    int residentSpEffectId3{ 0 };
    int materialSetId{ -1 };
    float partsDamageRate{ 1 };
    float corectSARecover{ 0 };
    int originEquipPro{ -1 };
    int originEquipPro1{ -1 };
    int originEquipPro2{ -1 };
    int originEquipPro3{ -1 };
    int originEquipPro4{ -1 };
    int originEquipPro5{ -1 };
    int originEquipPro6{ -1 };
    int originEquipPro7{ -1 };
    int originEquipPro8{ -1 };
    int originEquipPro9{ -1 };
    int originEquipPro10{ -1 };
    int originEquipPro11{ -1 };
    int originEquipPro12{ -1 };
    int originEquipPro13{ -1 };
    int originEquipPro14{ -1 };
    int originEquipPro15{ -1 };
    float faceScaleM_ScaleX{ 1 };
    float faceScaleM_ScaleZ{ 1 };
    float faceScaleM_MaxX{ 1 };
    float faceScaleM_MaxZ{ 1 };
    float faceScaleF_ScaleX{ 1 };
    float faceScaleF_ScaleZ{ 1 };
    float faceScaleF_MaxX{ 1 };
    float faceScaleF_MaxZ{ 1 };
    int qwcId{ -1 };
    unsigned short equipModelId{ 0 };
    unsigned short iconIdM{ 0 };
    unsigned short iconIdF{ 0 };
    unsigned short knockBack{ 0 };
    unsigned short knockbackBounceRate{ 0 };
    unsigned short durability{ 100 };
    unsigned short durabilityMax{ 100 };
    unsigned char pad03[2];
    unsigned short defFlickPower{ 0 };
    unsigned short defensePhysics{ 100 };
    unsigned short defenseMagic{ 100 };
    unsigned short defenseFire{ 100 };
    unsigned short defenseThunder{ 100 };
    short defenseSlash{ 0 };
    short defenseBlow{ 0 };
    short defenseThrust{ 0 };
    unsigned short resistPoison{ 100 };
    unsigned short resistDisease{ 100 };
    unsigned short resistBlood{ 100 };
    unsigned short resistCurse{ 100 };
    short reinforceTypeId{ 0 };
    short trophySGradeId{ -1 };
    short shopLv{ 0 };
    unsigned char knockbackParamId{ 0 };
    unsigned char flickDamageCutRate{ 0 };
    unsigned char equipModelCategory{ 1 };
    unsigned char equipModelGender{ 0 };
    unsigned char protectorCategory{ 0 };
    unsigned char rarity{ 0 };
    unsigned char sortGroupId{ 255 };
    unsigned char partsDmgType{ 0 };
    unsigned char pad04[2];
    bool isDeposit : 1 { false };
    bool headEquip : 1 { false };
    bool bodyEquip : 1 { false };
    bool armEquip : 1 { false };
    bool legEquip : 1 { false };
    bool useFaceScale : 1 { false };
    bool isSkipWeakDamageAnim : 1 { false };
    unsigned char pad06 : 1;
    unsigned char defenseMaterialVariationValue_Weak{ 0 };
    short autoFootEffectDecalBaseId2{ -1 };
    short autoFootEffectDecalBaseId3{ -1 };
    unsigned char defenseMaterialVariationValue{ 0 };
    bool isDiscard : 1 { false };
    bool isDrop : 1 { false };
    bool disableMultiDropShare : 1 { false };
    bool simpleModelForDlc : 1 { false };
    bool showLogCondType : 1 { true };
    unsigned char showDialogCondType : 2 { 2 };
    unsigned char pad : 1;
    float neutralDamageCutRate{ 1 };
    float slashDamageCutRate{ 1 };
    float blowDamageCutRate{ 1 };
    float thrustDamageCutRate{ 1 };
    float magicDamageCutRate{ 1 };
    float fireDamageCutRate{ 1 };
    float thunderDamageCutRate{ 1 };
    unsigned short defenseMaterialSfx1{ 50 };
    unsigned short defenseMaterialSfx_Weak1{ 50 };
    unsigned short defenseMaterial1{ 50 };
    unsigned short defenseMaterial_Weak1{ 50 };
    unsigned short defenseMaterialSfx2{ 50 };
    unsigned short defenseMaterialSfx_Weak2{ 50 };
    unsigned short footMaterialSe{ 139 };
    unsigned short defenseMaterial_Weak2{ 50 };
    int autoFootEffectDecalBaseId1{ -1 };
    float toughnessDamageCutRate{ 1 };
    float toughnessRecoverCorrection{ 0 };
    float darkDamageCutRate{ 1 };
    unsigned short defenseDark{ 100 };
    unsigned char invisibleFlag48 : 1;
    unsigned char invisibleFlag49 : 1;
    unsigned char invisibleFlag50 : 1;
    unsigned char invisibleFlag51 : 1;
    unsigned char invisibleFlag52 : 1;
    unsigned char invisibleFlag53 : 1;
    unsigned char invisibleFlag54 : 1;
    unsigned char invisibleFlag55 : 1;
    unsigned char invisibleFlag56 : 1;
    unsigned char invisibleFlag57 : 1;
    unsigned char invisibleFlag58 : 1;
    unsigned char invisibleFlag59 : 1;
    unsigned char invisibleFlag60 : 1;
    unsigned char invisibleFlag61 : 1;
    unsigned char invisibleFlag62 : 1;
    unsigned char invisibleFlag63 : 1;
    unsigned char invisibleFlag64 : 1;
    unsigned char invisibleFlag65 : 1;
    unsigned char invisibleFlag66 : 1;
    unsigned char invisibleFlag67 : 1;
    unsigned char invisibleFlag68 : 1;
    unsigned char invisibleFlag69 : 1;
    unsigned char invisibleFlag70 : 1;
    unsigned char invisibleFlag71 : 1;
    unsigned char invisibleFlag72 : 1;
    unsigned char invisibleFlag73 : 1;
    unsigned char invisibleFlag74 : 1;
    unsigned char invisibleFlag75 : 1;
    unsigned char invisibleFlag76 : 1;
    unsigned char invisibleFlag77 : 1;
    unsigned char invisibleFlag78 : 1;
    unsigned char invisibleFlag79 : 1;
    unsigned char invisibleFlag80 : 1;
    unsigned char padbit : 7;
    unsigned char postureControlId{ 0 };
    unsigned char pad2[4];
    int saleValue{ -1 };
    unsigned short resistFreeze{ 0 };
    unsigned char invisibleFlag_SexVer00{ 0 };
    unsigned char invisibleFlag_SexVer01{ 0 };
    unsigned char invisibleFlag_SexVer02{ 0 };
    unsigned char invisibleFlag_SexVer03{ 0 };
    unsigned char invisibleFlag_SexVer04{ 0 };
    unsigned char invisibleFlag_SexVer05{ 0 };
    unsigned char invisibleFlag_SexVer06{ 0 };
    unsigned char invisibleFlag_SexVer07{ 0 };
    unsigned char invisibleFlag_SexVer08{ 0 };
    unsigned char invisibleFlag_SexVer09{ 0 };
    unsigned char invisibleFlag_SexVer10{ 0 };
    unsigned char invisibleFlag_SexVer11{ 0 };
    unsigned char invisibleFlag_SexVer12{ 0 };
    unsigned char invisibleFlag_SexVer13{ 0 };
    unsigned char invisibleFlag_SexVer14{ 0 };
    unsigned char invisibleFlag_SexVer15{ 0 };
    unsigned char invisibleFlag_SexVer16{ 0 };
    unsigned char invisibleFlag_SexVer17{ 0 };
    unsigned char invisibleFlag_SexVer18{ 0 };
    unsigned char invisibleFlag_SexVer19{ 0 };
    unsigned char invisibleFlag_SexVer20{ 0 };
    unsigned char invisibleFlag_SexVer21{ 0 };
    unsigned char invisibleFlag_SexVer22{ 0 };
    unsigned char invisibleFlag_SexVer23{ 0 };
    unsigned char invisibleFlag_SexVer24{ 0 };
    unsigned char invisibleFlag_SexVer25{ 0 };
    unsigned char invisibleFlag_SexVer26{ 0 };
    unsigned char invisibleFlag_SexVer27{ 0 };
    unsigned char invisibleFlag_SexVer28{ 0 };
    unsigned char invisibleFlag_SexVer29{ 0 };
    unsigned char invisibleFlag_SexVer30{ 0 };
    unsigned char invisibleFlag_SexVer31{ 0 };
    unsigned char invisibleFlag_SexVer32{ 0 };
    unsigned char invisibleFlag_SexVer33{ 0 };
    unsigned char invisibleFlag_SexVer34{ 0 };
    unsigned char invisibleFlag_SexVer35{ 0 };
    unsigned char invisibleFlag_SexVer36{ 0 };
    unsigned char invisibleFlag_SexVer37{ 0 };
    unsigned char invisibleFlag_SexVer38{ 0 };
    unsigned char invisibleFlag_SexVer39{ 0 };
    unsigned char invisibleFlag_SexVer40{ 0 };
    unsigned char invisibleFlag_SexVer41{ 0 };
    unsigned char invisibleFlag_SexVer42{ 0 };
    unsigned char invisibleFlag_SexVer43{ 0 };
    unsigned char invisibleFlag_SexVer44{ 0 };
    unsigned char invisibleFlag_SexVer45{ 0 };
    unsigned char invisibleFlag_SexVer46{ 0 };
    unsigned char invisibleFlag_SexVer47{ 0 };
    unsigned char invisibleFlag_SexVer48{ 0 };
    unsigned char invisibleFlag_SexVer49{ 0 };
    unsigned char invisibleFlag_SexVer50{ 0 };
    unsigned char invisibleFlag_SexVer51{ 0 };
    unsigned char invisibleFlag_SexVer52{ 0 };
    unsigned char invisibleFlag_SexVer53{ 0 };
    unsigned char invisibleFlag_SexVer54{ 0 };
    unsigned char invisibleFlag_SexVer55{ 0 };
    unsigned char invisibleFlag_SexVer56{ 0 };
    unsigned char invisibleFlag_SexVer57{ 0 };
    unsigned char invisibleFlag_SexVer58{ 0 };
    unsigned char invisibleFlag_SexVer59{ 0 };
    unsigned char invisibleFlag_SexVer60{ 0 };
    unsigned char invisibleFlag_SexVer61{ 0 };
    unsigned char invisibleFlag_SexVer62{ 0 };
    unsigned char invisibleFlag_SexVer63{ 0 };
    unsigned char invisibleFlag_SexVer64{ 0 };
    unsigned char invisibleFlag_SexVer65{ 0 };
    unsigned char invisibleFlag_SexVer66{ 0 };
    unsigned char invisibleFlag_SexVer67{ 0 };
    unsigned char invisibleFlag_SexVer68{ 0 };
    unsigned char invisibleFlag_SexVer69{ 0 };
    unsigned char invisibleFlag_SexVer70{ 0 };
    unsigned char invisibleFlag_SexVer71{ 0 };
    unsigned char invisibleFlag_SexVer72{ 0 };
    unsigned char invisibleFlag_SexVer73{ 0 };
    unsigned char invisibleFlag_SexVer74{ 0 };
    unsigned char invisibleFlag_SexVer75{ 0 };
    unsigned char invisibleFlag_SexVer76{ 0 };
    unsigned char invisibleFlag_SexVer77{ 0 };
    unsigned char invisibleFlag_SexVer78{ 0 };
    unsigned char invisibleFlag_SexVer79{ 0 };
    unsigned char invisibleFlag_SexVer80{ 0 };
    unsigned char invisibleFlag_SexVer81{ 0 };
    unsigned char invisibleFlag_SexVer82{ 0 };
    unsigned char invisibleFlag_SexVer83{ 0 };
    unsigned char invisibleFlag_SexVer84{ 0 };
    unsigned char invisibleFlag_SexVer85{ 0 };
    unsigned char invisibleFlag_SexVer86{ 0 };
    unsigned char invisibleFlag_SexVer87{ 0 };
    unsigned char invisibleFlag_SexVer88{ 0 };
    unsigned char invisibleFlag_SexVer89{ 0 };
    unsigned char invisibleFlag_SexVer90{ 0 };
    unsigned char invisibleFlag_SexVer91{ 0 };
    unsigned char invisibleFlag_SexVer92{ 0 };
    unsigned char invisibleFlag_SexVer93{ 0 };
    unsigned char invisibleFlag_SexVer94{ 0 };
    unsigned char invisibleFlag_SexVer95{ 0 };
    unsigned char pad404[14];
};

}; // namespace paramdefs
}; // namespace from

static_assert(sizeof(from::paramdefs::EQUIP_PARAM_PROTECTOR_ST) == 416,
    "EQUIP_PARAM_PROTECTOR_ST paramdef size does not match detected size");
