name: Generate Doxygen Documentation

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.8
      with:
          doxyfile-path: ./Doxyfile
          working-directory: .
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
